//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stolovayaa.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyReport
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int TotalOrders { get; set; }
        public decimal TotalAmount { get; set; }
        public string MostPopularDish { get; set; }
    }
}
