//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stolovayaa.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersItems
    {
        public int ID { get; set; }
        public int OrdersID { get; set; }
        public int DishesID { get; set; }
        public int Count { get; set; }
        public decimal PriceAtOrder { get; set; }
    
        public virtual Dishes Dishes { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
